# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

#    - name: Create .env file
#      run: |
#        touch .env
#        echo REACT_APP_GOOGLE_CLIENT_ID = ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} >> .env

    - name: Install dependencies
      run: npm install
    # - run: npm run build --if-present
    - name: Run tests
      run: npm test

    - name: "Say Hello Mona it's Monday"
      run: echo "Hello $First_Name. Today is $REACT_APP_MONETA_API_BASE_URL!"
      env:
        First_Name: Mona

    - name: Publish github pages
      run: |
        git config --global user.email ${{secrets.GH_EMAIL}}
        git config --global user.name ${{secrets.GH_USERNAME}}
        git remote set-url origin https://${{secrets.GH_PERSONAL_TOKEN}}@github.com/${{secrets.GH_USERNAME}}/muneem.git
        npm run deploy

